services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: relay
      POSTGRES_PASSWORD: relay
      POSTGRES_DB: relay
    ports:
      - "5432:5432"
    volumes:
      - relay_postgres_data:/var/lib/postgresql/data

  mongo1:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - relay_mongo1_data:/data/db

  mongo2:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - relay_mongo2_data:/data/db

volumes:
  relay_postgres_data:
  relay_mongo1_data:
  relay_mongo2_data:
